### ISSUE TITLE
The field must contain a valid time

### ISSUE THREAD

**Issue by jerearaujo03** [laraning/nova-time-field#50]
- Laravel Version: 7.29.3
- Nova Version: 3.15.9
- PHP Version: 7.4.3
- Database Driver & Version: Mysql 8.0.22
- Operating System and Version:Ubuntu 20.04.1 LTS

### Description:
I moved my project from dev (MacOS 11.0.1) to prod (Ubuntu 20.04.1) and now my DateTime field doesn't work. Here is the log:

```
[2020-11-19 11:40:30] production.ERROR: The field must contain a valid time. {"userId":1,"exception":"[object] (Exception(code: 0): The field must contain a valid time. at /var/www/skyride/vendor/laraning/nova-time-field/src/TimeField.php:89)
[stacktrace]
#0 /var/www/skyride/vendor/laravel/nova/src/Fields/Field.php(362): Laraning\\NovaTimeField\\TimeField->fillAttributeFromRequest()
#1 /var/www/skyride/vendor/laravel/nova/src/Fields/Field.php(341): Laravel\\Nova\\Fields\\Field->fillAttribute()
#2 /var/www/skyride/vendor/laravel/nova/src/Fields/Field.php(315): Laravel\\Nova\\Fields\\Field->fillInto()
#3 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(60): Laravel\\Nova\\Fields\\Field->fill()
#4 [internal function]: Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}()
#5 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map()
#6 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(61): Illuminate\\Support\\Collection->map()
#7 /var/www/skyride/vendor/laravel/nova/src/FillsFields.php(85): Illuminate\\Support\\HigherOrderCollectionProxy->__call()
#8 /var/www/skyride/app/Nova/Resource.php(82): Laravel\\Nova\\Resource::fillFields()
#9 /var/www/skyride/vendor/laravel/nova/src/Http/Controllers/ResourceStoreController.php(28): App\\Nova\\Resource::fill()
#10 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(28): Laravel\\Nova\\Http\\Controllers\\ResourceStoreController->Laravel\\Nova\\Http\\Controllers\\{closure}()
#11 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(367): Illuminate\\Database\\Connection->transaction()
#12 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Database\\DatabaseManager->__call()
#13 /var/www/skyride/vendor/laravel/nova/src/Http/Controllers/ResourceStoreController.php(44): Illuminate\\Support\\Facades\\Facade::__callStatic()
#14 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Laravel\\Nova\\Http\\Controllers\\ResourceStoreController->handle()
#15 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#16 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#17 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#18 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#19 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#20 /var/www/skyride/vendor/vyuldashev/nova-permission/src/ForgetCachedPermissions.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Vyuldashev\\NovaPermission\\ForgetCachedPermissions->handle()
#22 /var/www/skyride/vendor/laravel/nova/src/Http/Middleware/Authorize.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\Authorize->handle()
#24 /var/www/skyride/vendor/laravel/nova/src/Http/Middleware/BootTools.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\BootTools->handle()
#26 /var/www/skyride/vendor/laravel/nova/src/Http/Middleware/DispatchServingNovaEvent.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\DispatchServingNovaEvent->handle()
#28 /var/www/skyride/app/Http/Middleware/CheckNovaAdmin.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\CheckNovaAdmin->handle()
#30 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#32 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/skyride/vendor/laravel/nova/src/Http/Middleware/Authenticate.php(31): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#34 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\Authenticate->handle()
#35 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#37 /var/www/skyride/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#39 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#41 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#42 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#44 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#46 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()
#48 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
#49 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()
#50 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
#51 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
#52 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#53 /var/www/skyride/vendor/laravel/nova/src/Http/Middleware/ServeNova.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle()
#55 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#57 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#59 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#61 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#63 /var/www/skyride/vendor/fruitcake/laravel-cors/src/HandleCors.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#65 /var/www/skyride/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#67 /var/www/skyride/vendor/fruitcake/laravel-cors/src/HandleCors.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#69 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#70 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
#71 /var/www/skyride/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#72 /var/www/skyride/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#73 {main}
"} 

```

**Comment by laraning** [comment]
Can you print the codebase too? Thx

**Comment by jerearaujo03** [comment]
```
<?php

namespace App\Nova;

...
use Laraning\NovaTimeField\TimeField;
...

class Tour extends Resource
{
    ...
    public function fields(Request $request)
    {
        return [
            ...
            TimeField::make('Duración', 'duration')
                ->hideFromIndex(),
            ...
        ]
    }
}
```

Should I have to cast the column in the model? (it's TIME mysql's type)

**Comment by hananloser** [comment]
> ```
> <?php
> 
> namespace App\Nova;
> 
> ...
> use Laraning\NovaTimeField\TimeField;
> ...
> 
> class Tour extends Resource
> {
>     ...
>     public function fields(Request $request)
>     {
>         return [
>             ...
>             TimeField::make('Duración', 'duration')
>                 ->hideFromIndex(),
>             ...
>         ]
>     }
> }
> ```
> 
> Should I have to cast the column in the model? (it's TIME mysql's type)

same issue i dont know how to cast this field i am try using time datetime still error

**Comment by laraning** [comment]
Thanks , will check it tomorrow

**Comment by brunocfalcao** [comment]
Hi,

You might need to cast the field yes. It's a datetime casting. Did you try it out?

On your model, you need to have something like:

```php

protected $casts = [

'duration' => 'datetime'

];

**Comment by souri84** [comment]
same issue... cast doesn't work

**Comment by martio** [comment]
Same issue :(

**Comment by Loown** [comment]
Experimenting the same issue

Seems like default value isn't null

**Comment by brunocfalcao** [comment]
@loown what Nova version are you using ? Any specific errors that appear on your log ?

It's very difficult to spot this bug without more data, since I made a test on the latest version and everything is working fine ...

**Comment by dantos** [comment]
Same issue here, using laravel nova version 3.8.1

**Comment by philipbaginski** [comment]
The same issue, discovered today. Nova 3.20

**Comment by philipbaginski** [comment]
Fixed: This code does not work:

TimeField::make('Time', 'start_time')
                ->rules('nullable')
                ->minuteIncrement(5),

, but this one works:

TimeField::make('Time', 'start_time')
                ->nullable()
                ->rules('nullable')
                ->minuteIncrement(5),

Enjoy :-)

**Comment by laraning** [comment]
Thanks, will really check it this night, and try to release a new version

**Comment by 949mac** [comment]
Same issue for me today.

**Comment by laraning** [comment]
As a quick update, I am refactoring the time field codebase, hopefully to resolve these issues. Will be back when I have a new version very soon
